export const ACTIVITIES_EMOJIS: [string, string][] = [
  ["🎟️", "admission tickets"],
  ["🎫", "ticket"],
  ["🎖️", "military medal"],
  ["🏆", "trophy"],
  ["🏅", "sports medal"],
  ["🥇", "1st place medal"],
  ["🥈", "2nd place medal"],
  ["🥉", "3rd place medal"],
  ["⚽", "soccer ball"],
  ["⚾", "baseball"],
  ["🥎", "softball"],
  ["🏀", "basketball"],
  ["🏐", "volleyball"],
  ["🏈", "american football"],
  ["🏉", "rugby football"],
  ["🎾", "tennis"],
  ["🥏", "flying disc"],
  ["🎳", "bowling"],
  ["🏏", "cricket game"],
  ["🏑", "field hockey"],
  ["🏒", "ice hockey"],
  ["🥍", "lacrosse"],
  ["🏓", "ping pong"],
  ["🏸", "badminton"],
  ["🥊", "boxing glove"],
  ["🥋", "martial arts uniform"],
  ["🥅", "goal net"],
  ["⛳", "flag in hole"],
  ["⛸️", "ice skate"],
  ["🎣", "fishing pole"],
  ["🤿", "diving mask"],
  ["🎽", "running shirt"],
  ["🎿", "skis"],
  ["🛷", "sled"],
  ["🥌", "curling stone"],
  ["🎯", "bullseye"],
  ["🪀", "yo-yo"],
  ["🪁", "kite"],
  ["🔫", "water pistol"],
  ["🎱", "pool 8 ball"],
  ["🔮", "crystal ball"],
  ["🪄", "magic wand"],
  ["🎮", "video game"],
  ["🕹️", "joystick"],
  ["🎰", "slot machine"],
  ["🎲", "game die"],
  ["♟️", "chess pawn"],
  ["🧩", "puzzle piece"],
  ["🪅", "piñata"],
  ["🪩", "mirror ball"],
  ["🎼", "musical score"],
  ["🎵", "musical note"],
  ["🎶", "musical notes"],
  ["🎙️", "studio microphone"],
  ["🎚️", "level slider"],
  ["🎚", "level slider"],
  ["🎛️", "control knobs"],
  ["🎛", "control knobs"],
  ["🎤", "microphone"],
  ["🎧", "headphone"],
  ["📻", "radio"],
  ["🎷", "saxophone"],
  ["🪗", "accordion"],
  ["🎸", "guitar"],
  ["🎹", "musical keyboard"],
  ["🎺", "trumpet"],
  ["🎻", "violin"],
  ["🪕", "banjo"],
  ["🥁", "drum"],
  ["🪘", "long drum"],
  ["🪇", "maracas"],
  ["🪈", "flute"],
  ["📱", "mobile phone"],
  ["📲", "mobile phone with arrow"],
  ["🏗️", "building construction"],
  ["🏗", "building construction"],
];
