export const ANIMAL_AND_NATURE_EMOJIS: [string, string][] = [
  ["🐵", "monkey face"],
  ["🐒", "monkey"],
  ["🦍", "gorilla"],
  ["🦧", "orangutan"],
  ["🐶", "dog face"],
  ["🐕", "dog"],
  ["🦮", "guide dog"],
  ["🐕‍🦺", "service dog"],
  ["🐩", "poodle"],
  ["🐺", "wolf"],
  ["🦊", "fox"],
  ["🦝", "raccoon"],
  ["🐱", "cat face"],
  ["🐈", "cat"],
  ["🐈‍⬛", "black cat"],
  ["🦁", "lion"],
  ["🐯", "tiger face"],
  ["🐅", "tiger"],
  ["🐆", "leopard"],
  ["🐴", "horse face"],
  ["🫎", "moose"],
  ["🫏", "donkey"],
  ["🐎", "horse"],
  ["🦄", "unicorn"],
  ["🦓", "zebra"],
  ["🦌", "deer"],
  ["🦬", "bison"],
  ["🐮", "cow face"],
  ["🐂", "ox"],
  ["🐃", "water buffalo"],
  ["🐄", "cow"],
  ["🐷", "pig face"],
  ["🐖", "pig"],
  ["🐗", "boar"],
  ["🐽", "pig nose"],
  ["🐏", "ram"],
  ["🐑", "ewe"],
  ["🐐", "goat"],
  ["🐪", "camel"],
  ["🐫", "two-hump camel"],
  ["🦙", "llama"],
  ["🦒", "giraffe"],
  ["🐘", "elephant"],
  ["🦣", "mammoth"],
  ["🦏", "rhinoceros"],
  ["🦛", "hippopotamus"],
  ["🐭", "mouse face"],
  ["🐁", "mouse"],
  ["🐀", "rat"],
  ["🐹", "hamster"],
  ["🐰", "rabbit face"],
  ["🐇", "rabbit"],
  ["🐿️", "chipmunk"],
  ["🐿", "chipmunk"],
  ["🦫", "beaver"],
  ["🦔", "hedgehog"],
  ["🦇", "bat"],
  ["🐻", "bear"],
  ["🐻‍❄️", "polar bear"],
  ["🐻‍❄", "polar bear"],
  ["🐨", "koala"],
  ["🐼", "panda"],
  ["🦥", "sloth"],
  ["🦦", "otter"],
  ["🦨", "skunk"],
  ["🦘", "kangaroo"],
  ["🦡", "badger"],
  ["🐾", "paw prints"],
  ["🦃", "turkey"],
  ["🐔", "chicken"],
  ["🐓", "rooster"],
  ["🐣", "hatching chick"],
  ["🐤", "baby chick"],
  ["🐥", "front-facing baby chick"],
  ["🐦", "bird"],
  ["🐧", "penguin"],
  ["🕊️", "dove"],
  ["🕊", "dove"],
  ["🦅", "eagle"],
  ["🦆", "duck"],
  ["🦢", "swan"],
  ["🦉", "owl"],
  ["🦤", "dodo"],
  ["🪶", "feather"],
  ["🦩", "flamingo"],
  ["🦚", "peacock"],
  ["🦜", "parrot"],
  ["🪽", "wing"],
  ["🐦‍⬛", "black bird"],
  ["🪿", "goose"],
  ["🐸", "frog"],
  ["🐊", "crocodile"],
  ["🐢", "turtle"],
  ["🦎", "lizard"],
  ["🐍", "snake"],
  ["🐲", "dragon face"],
  ["🐉", "dragon"],
  ["🦕", "sauropod"],
  ["🦖", "T-Rex"],
  ["🐳", "spouting whale"],
  ["🐋", "whale"],
  ["🐬", "dolphin"],
  ["🦭", "seal"],
  ["🐟", "fish"],
  ["🐠", "tropical fish"],
  ["🐡", "blowfish"],
  ["🦈", "shark"],
  ["🐙", "octopus"],
  ["🐚", "spiral shell"],
  ["🪸", "coral"],
  ["🪼", "jellyfish"],
  ["🐌", "snail"],
  ["🦋", "butterfly"],
  ["🐛", "bug"],
  ["🐜", "ant"],
  ["🐝", "honeybee"],
  ["🪲", "beetle"],
  ["🐞", "lady beetle"],
  ["🦗", "cricket"],
  ["🪳", "cockroach"],
  ["🕷️", "spider"],
  ["🕷", "spider"],
  ["🕸️", "spider web"],
  ["🕸", "spider web"],
  ["🦂", "scorpion"],
  ["🦟", "mosquito"],
  ["🪰", "fly"],
  ["🪱", "worm"],
  ["🦠", "microbe"],
  ["💐", "bouquet"],
  ["🌸", "cherry blossom"],
  ["💮", "white flower"],
  ["🪷", "lotus"],
  ["🏵️", "rosette"],
  ["🏵", "rosette"],
  ["🌹", "rose"],
  ["🥀", "wilted flower"],
  ["🌺", "hibiscus"],
  ["🌻", "sunflower"],
  ["🌼", "blossom"],
  ["🌷", "tulip"],
  ["🪻", "hyacinth"],
  ["🌱", "seedling"],
  ["🪴", "potted plant"],
  ["🌲", "evergreen tree"],
  ["🌳", "deciduous tree"],
  ["🌴", "palm tree"],
  ["🌵", "cactus"],
  ["🌾", "sheaf of rice"],
  ["🌿", "herb"],
  ["☘️", "shamrock"],
  ["☘", "shamrock"],
  ["🍀", "four leaf clover"],
  ["🍁", "maple leaf"],
  ["🍂", "fallen leaf"],
  ["🍃", "leaf fluttering in wind"],
  ["🪹", "empty nest"],
  ["🪺", "nest with eggs"],
  ["🍄", "mushroom"],
  ["🍇", "grapes"],
  ["🍈", "melon"],
  ["🍉", "watermelon"],
  ["🍊", "tangerine"],
  ["🍋", "lemon"],
  ["🍌", "banana"],
  ["🍍", "pineapple"],
  ["🥭", "mango"],
  ["🍎", "red apple"],
  ["🍏", "green apple"],
  ["🍐", "pear"],
  ["🍑", "peach"],
  ["🍒", "cherries"],
  ["🍓", "strawberry"],
  ["🫐", "blueberries"],
  ["🥝", "kiwi fruit"],
  ["🍅", "tomato"],
  ["🫒", "olive"],
  ["🥥", "coconut"],
  ["🥑", "avocado"],
  ["🍆", "eggplant"],
  ["🥔", "potato"],
  ["🥕", "carrot"],
  ["🌽", "ear of corn"],
  ["🌶️", "hot pepper"],
  ["🌶", "hot pepper"],
  ["🫑", "bell pepper"],
  ["🥒", "cucumber"],
  ["🥬", "leafy green"],
  ["🥦", "broccoli"],
  ["🧄", "garlic"],
  ["🧅", "onion"],
  ["🥜", "peanuts"],
  ["🫘", "beans"],
  ["🌰", "chestnut"],
  ["🫚", "ginger root"],
  ["🫛", "pea pod"],
  ["☀️", "sun"],
  ["🌝", "full moon face"],
  ["🌞", "sun with face"],
  ["🪐", "ringed planet"],
  ["⭐", "star"],
  ["🌟", "glowing star"],
  ["🌠", "shooting star"],
  ["🌌", "milky way"],
  ["☁️", "cloud"],
  ["⛅", "sun behind cloud"],
  ["⛈️", "cloud with lightning and rain"],
  ["🌤️", "sun behind small cloud"],
  ["🌥️", "sun behind large cloud"],
  ["🌦️", "sun behind rain cloud"],
  ["🌧️", "cloud with rain"],
  ["🌨️", "cloud with snow"],
  ["🌩️", "cloud with lightning"],
  ["🌪️", "tornado"],
  ["🌫️", "fog"],
  ["🌬️", "wind face"],
  ["🌀", "cyclone"],
  ["🌈", "rainbow"],
  ["🌑", "new moon"],
  ["🌒", "waxing crescent moon"],
  ["🌓", "first quarter moon"],
  ["🌔", "waxing gibbous moon"],
  ["🌕", "full moon"],
  ["🌖", "waning gibbous moon"],
  ["🌗", "last quarter moon"],
  ["🌘", "waning crescent moon"],
  ["🌙", "crescent moon"],
  ["🌚", "new moon face"],
  ["🌛", "first quarter moon face"],
  ["🌜", "last quarter moon face"],
  ["❄️", "snowflake"],
  ["☃", "snowman"],
  ["⛄", "snowman without snow"],
  ["☄️", "comet"],
  ["🔥", "fire"],
  ["💧", "droplet"],
  ["🌊", "water wave"],
];
