export const OBJECTS_EMOJIS: [string, string][] = [
  ["🧸", "teddy bear"],
  ["🧧", "red envelope"],
  ["🎀", "ribbon"],
  ["🎁", "wrapped gift"],
  ["🎗️", "reminder ribbon"],
  ["🎗", "reminder ribbon"],
  ["🪆", "nesting dolls"],
  ["🃏", "joker"],
  ["🀄", "mahjong red dragon"],
  ["🎴", "flower playing cards"],
  ["🎭", "performing arts"],
  ["🖼️", "framed picture"],
  ["🖼", "framed picture"],
  ["🎨", "artist palette"],
  ["🧵", "thread"],
  ["🪡", "sewing needle"],
  ["🧶", "yarn"],
  ["🪢", "knot"],
  ["👓", "glasses"],
  ["🕶️", "sunglasses"],
  ["🕶", "sunglasses"],
  ["🥽", "goggles"],
  ["🥼", "lab coat"],
  ["🦺", "safety vest"],
  ["👔", "necktie"],
  ["👕", "t-shirt"],
  ["👖", "jeans"],
  ["🧣", "scarf"],
  ["🧤", "gloves"],
  ["🧥", "coat"],
  ["🧦", "socks"],
  ["👗", "dress"],
  ["👘", "kimono"],
  ["🥻", "sari"],
  ["🩱", "one-piece swimsuit"],
  ["🩲", "briefs"],
  ["🩳", "shorts"],
  ["👙", "bikini"],
  ["👚", "woman’s clothes"],
  ["🪭", "folding hand fan"],
  ["👛", "purse"],
  ["👜", "handbag"],
  ["👝", "clutch bag"],
  ["🛍️", "shopping bags"],
  ["🛍", "shopping bags"],
  ["🎒", "backpack"],
  ["🩴", "thong sandal"],
  ["👞", "man’s shoe"],
  ["👟", "running shoe"],
  ["🥾", "hiking boot"],
  ["🥿", "flat shoe"],
  ["👠", "high-heeled shoe"],
  ["👡", "woman’s sandal"],
  ["🩰", "ballet shoes"],
  ["👢", "woman’s boot"],
  ["🪮", "hair pick"],
  ["👑", "crown"],
  ["👒", "woman’s hat"],
  ["🎩", "top hat"],
  ["🎓", "graduation cap"],
  ["🧢", "billed cap"],
  ["🪖", "military helmet"],
  ["⛑️", "rescue worker’s helmet"],
  ["⛑", "rescue worker’s helmet"],
  ["📿", "prayer beads"],
  ["💄", "lipstick"],
  ["💍", "ring"],
  ["💎", "gem stone"],
  ["🔇", "muted speaker"],
  ["🔈", "speaker low volume"],
  ["🔉", "speaker medium volume"],
  ["🔊", "speaker high volume"],
  ["📢", "loudspeaker"],
  ["📣", "megaphone"],
  ["📯", "postal horn"],
  ["🔔", "bell"],
  ["🔕", "bell with slash"],
  ["☎️", "telephone"],
  ["☎", "telephone"],
  ["📞", "telephone receiver"],
  ["📟", "pager"],
  ["📠", "fax machine"],
  ["🔋", "battery"],
  ["🪫", "low battery"],
  ["🔌", "electric plug"],
  ["💻", "laptop"],
  ["🖥️", "desktop computer"],
  ["🖥", "desktop computer"],
  ["🖨️", "printer"],
  ["🖨", "printer"],
  ["⌨️", "keyboard"],
  ["⌨", "keyboard"],
  ["🖱️", "computer mouse"],
  ["🖱", "computer mouse"],
  ["🖲️", "trackball"],
  ["🖲", "trackball"],
  ["💽", "computer disk"],
  ["💾", "floppy disk"],
  ["💿", "optical disk"],
  ["📀", "dvd"],
  ["🧮", "abacus"],
  ["🎥", "movie camera"],
  ["🎞️", "film frames"],
  ["🎞", "film frames"],
  ["📽️", "film projector"],
  ["📽", "film projector"],
  ["🎬", "clapper board"],
  ["📺", "television"],
  ["📷", "camera"],
  ["📸", "camera with flash"],
  ["📹", "video camera"],
  ["📼", "videocassette"],
  ["🔍", "magnifying glass tilted left"],
  ["🔎", "magnifying glass tilted right"],
  ["🕯️", "candle"],
  ["🕯", "candle"],
  ["💡", "light bulb"],
  ["🔦", "flashlight"],
  ["🏮", "red paper lantern"],
  ["🪔", "diya lamp"],
  ["📔", "notebook with decorative cover"],
  ["📕", "closed book"],
  ["📖", "open book"],
  ["📗", "green book"],
  ["📘", "blue book"],
  ["📙", "orange book"],
  ["📚", "books"],
  ["📓", "notebook"],
  ["📒", "ledger"],
  ["📃", "page with curl"],
  ["📜", "scroll"],
  ["📄", "page facing up"],
  ["📰", "newspaper"],
  ["🗞️", "rolled-up newspaper"],
  ["🗞", "rolled-up newspaper"],
  ["📑", "bookmark tabs"],
  ["🔖", "bookmark"],
  ["🏷️", "label"],
  ["🏷", "label"],
  ["💰", "money bag"],
  ["🪙", "coin"],
  ["💴", "yen banknote"],
  ["💵", "dollar banknote"],
  ["💶", "euro banknote"],
  ["💷", "pound banknote"],
  ["💸", "money with wings"],
  ["💳", "credit card"],
  ["🧾", "receipt"],
  ["💹", "chart increasing with yen"],
  ["✉️", "envelope"],
  ["✉", "envelope"],
  ["📧", "e-mail"],
  ["📨", "incoming envelope"],
  ["📩", "envelope with arrow"],
  ["📤", "outbox tray"],
  ["📥", "inbox tray"],
  ["📦", "package"],
  ["📫", "closed mailbox with raised flag"],
  ["📪", "closed mailbox with lowered flag"],
  ["📬", "open mailbox with raised flag"],
  ["📭", "open mailbox with lowered flag"],
  ["📮", "postbox"],
  ["🗳️", "ballot box with ballot"],
  ["🗳", "ballot box with ballot"],
  ["✏️", "pencil"],
  ["✏", "pencil"],
  ["✒️", "black nib"],
  ["✒", "black nib"],
  ["🖋️", "fountain pen"],
  ["🖋", "fountain pen"],
  ["🖊️", "pen"],
  ["🖊", "pen"],
  ["🖌️", "paintbrush"],
  ["🖌", "paintbrush"],
  ["🖍️", "crayon"],
  ["🖍", "crayon"],
  ["📝", "memo"],
  ["💼", "briefcase"],
  ["📁", "file folder"],
  ["📂", "open file folder"],
  ["🗂️", "card index dividers"],
  ["🗂", "card index dividers"],
  ["📅", "calendar"],
  ["📆", "tear-off calendar"],
  ["🗒️", "spiral notepad"],
  ["🗒", "spiral notepad"],
  ["🗓️", "spiral calendar"],
  ["🗓", "spiral calendar"],
  ["📇", "card index"],
  ["📈", "chart increasing"],
  ["📉", "chart decreasing"],
  ["📊", "bar chart"],
  ["📋", "clipboard"],
  ["📌", "pushpin"],
  ["📍", "round pushpin"],
  ["📎", "paperclip"],
  ["🖇️", "linked paperclips"],
  ["🖇", "linked paperclips"],
  ["📏", "straight ruler"],
  ["📐", "triangular ruler"],
  ["✂️", "scissors"],
  ["✂", "scissors"],
  ["🗃️", "card file box"],
  ["🗃", "card file box"],
  ["🗄️", "file cabinet"],
  ["🗄", "file cabinet"],
  ["🗑️", "wastebasket"],
  ["🗑", "wastebasket"],
  ["🔒", "locked"],
  ["🔓", "unlocked"],
  ["🔏", "locked with pen"],
  ["🔐", "locked with key"],
  ["🔑", "key"],
  ["🗝️", "old key"],
  ["🗝", "old key"],
  ["🔨", "hammer"],
  ["🪓", "axe"],
  ["⛏️", "pick"],
  ["⛏", "pick"],
  ["⚒️", "hammer and pick"],
  ["⚒", "hammer and pick"],
  ["🛠️", "hammer and wrench"],
  ["🛠", "hammer and wrench"],
  ["🗡️", "dagger"],
  ["🗡", "dagger"],
  ["⚔️", "crossed swords"],
  ["⚔", "crossed swords"],
  ["💣", "bomb"],
  ["🪃", "boomerang"],
  ["🏹", "bow and arrow"],
  ["🛡️", "shield"],
  ["🛡", "shield"],
  ["🪚", "carpentry saw"],
  ["🔧", "wrench"],
  ["🪛", "screwdriver"],
  ["🔩", "nut and bolt"],
  ["⚙️", "gear"],
  ["⚙", "gear"],
  ["🗜️", "clamp"],
  ["🗜", "clamp"],
  ["⚖️", "balance scale"],
  ["⚖", "balance scale"],
  ["🦯", "white cane"],
  ["🔗", "link"],
  ["⛓️", "chains"],
  ["⛓", "chains"],
  ["🪝", "hook"],
  ["🧰", "toolbox"],
  ["🧲", "magnet"],
  ["🪜", "ladder"],
  ["⚗️", "alembic"],
  ["⚗", "alembic"],
  ["🧪", "test tube"],
  ["🧫", "petri dish"],
  ["🧬", "dna"],
  ["🔬", "microscope"],
  ["🔭", "telescope"],
  ["📡", "satellite antenna"],
  ["💉", "syringe"],
  ["🩸", "drop of blood"],
  ["💊", "pill"],
  ["🩹", "adhesive bandage"],
  ["🩼", "crutch"],
  ["🩺", "stethoscope"],
  ["🩻", "x-ray"],
  ["🚪", "door"],
  ["🛗", "elevator"],
  ["🪞", "mirror"],
  ["🪟", "window"],
  ["🛏️", "bed"],
  ["🛏", "bed"],
  ["🛋️", "couch and lamp"],
  ["🛋", "couch and lamp"],
  ["🪑", "chair"],
  ["🚽", "toilet"],
  ["🪠", "plunger"],
  ["🚿", "shower"],
  ["🛁", "bathtub"],
  ["🪤", "mouse trap"],
  ["🪒", "razor"],
  ["🧴", "lotion bottle"],
  ["🧷", "safety pin"],
  ["🧹", "broom"],
  ["🧺", "basket"],
  ["🧻", "roll of paper"],
  ["🪣", "bucket"],
  ["🧼", "soap"],
  ["🫧", "bubbles"],
  ["🪥", "toothbrush"],
  ["🧽", "sponge"],
  ["🧯", "fire extinguisher"],
  ["🛒", "shopping cart"],
  ["🚬", "cigarette"],
  ["⚰️", "coffin"],
  ["⚰", "coffin"],
  ["🪦", "headstone"],
  ["⚱️", "funeral urn"],
  ["⚱", "funeral urn"],
  ["🧱", "brick"],
  ["🪨", "rock"],
  ["🪵", "wood"],
  ["🛢️", "oil drum"],
  ["🛢", "oil drum"],
  ["⛽", "fuel pump"],
  ["🛞", "wheel"],
  ["🚨", "police car light"],
  ["🚥", "horizontal traffic light"],
  ["🚦", "vertical traffic light"],
  ["🛑", "stop sign"],
  ["🚧", "construction"],
  ["⚓", "anchor"],
  ["🛟", "ring buoy"],
  ["🛰️", "satellite"],
  ["🛰", "satellite"],
  ["🚀", "rocket"],
  ["🛸", "flying saucer"],
  ["🛎️", "bellhop bell"],
  ["🛎", "bellhop bell"],
  ["🧳", "luggage"],
  ["⌛", "hourglass done"],
  ["⏳", "hourglass not done"],
  ["⌚", "watch"],
  ["⏰", "alarm clock"],
  ["⏱️", "stopwatch"],
  ["⏱", "stopwatch"],
  ["⏲️", "timer clock"],
  ["⏲", "timer clock"],
  ["🕰️", "mantelpiece clock"],
  ["🕰", "mantelpiece clock"],
  ["🕛", "twelve o’clock"],
  ["🕧", "twelve-thirty"],
  ["🕐", "one o’clock"],
  ["🕜", "one-thirty"],
  ["🕑", "two o’clock"],
  ["🕝", "two-thirty"],
  ["🕒", "three o’clock"],
  ["🕞", "three-thirty"],
  ["🕓", "four o’clock"],
  ["🕟", "four-thirty"],
  ["🕔", "five o’clock"],
  ["🕠", "five-thirty"],
  ["🕕", "six o’clock"],
  ["🕡", "six-thirty"],
  ["🕖", "seven o’clock"],
  ["🕢", "seven-thirty"],
  ["🕗", "eight o’clock"],
  ["🕣", "eight-thirty"],
  ["🕘", "nine o’clock"],
  ["🕤", "nine-thirty"],
  ["🕙", "ten o’clock"],
  ["🕥", "ten-thirty"],
  ["🕚", "eleven o’clock"],
  ["🕦", "eleven-thirty"],
  ["🌡️", "thermometer"],
  ["🌂", "closed umbrella"],
  ["☂️", "umbrella"],
  ["☔", "umbrella with rain drops"],
  ["⛱️", "umbrella on ground"],
  ["⚡", "high voltage"],
  ["🎃", "jack-o-lantern"],
  ["🎄", "Christmas tree"],
  ["🎆", "fireworks"],
  ["🎇", "sparkler"],
  ["🧨", "firecracker"],
  ["✨", "sparkles"],
  ["🎈", "balloon"],
  ["🎉", "party popper"],
  ["🎊", "confetti ball"],
  ["🎋", "tanabata tree"],
  ["🎍", "pine decoration"],
  ["🎎", "Japanese dolls"],
  ["🎏", "carp streamer"],
  ["🎐", "wind chime"],
];
