export const TRAVEL_AND_PLACES_EMOJIS: [string, string][] = [
  ["🌍", "globe showing Europe-Africa"],
  ["🌎", "globe showing Americas"],
  ["🌏", "globe showing Asia-Australia"],
  ["🌐", "globe with meridians"],
  ["🗺️", "world map"],
  ["🗺", "world map"],
  ["🗾", "map of Japan"],
  ["🧭", "compass"],
  ["🏔️", "snow-capped mountain"],
  ["🏔", "snow-capped mountain"],
  ["⛰️", "mountain"],
  ["⛰", "mountain"],
  ["🌋", "volcano"],
  ["🗻", "mount fuji"],
  ["🏕️", "camping"],
  ["🏖️", "beach with umbrella"],
  ["🏜️", "desert"],
  ["🏝️", "desert island"],
  ["🏞️", "national park"],
  ["🏟️", "stadium"],
  ["🏛️", "classical building"],
  ["🛖", "hut"],
  ["🏘️", "houses"],
  ["🏚️", "derelict house"],
  ["🏠", "house"],
  ["🏡", "house with garden"],
  ["🏢", "office building"],
  ["🏣", "Japanese post office"],
  ["🏤", "post office"],
  ["🏥", "hospital"],
  ["🏦", "bank"],
  ["🏨", "hotel"],
  ["🏩", "love hotel"],
  ["🏪", "convenience store"],
  ["🏫", "school"],
  ["🏬", "department store"],
  ["🏭", "factory"],
  ["🏯", "Japanese castle"],
  ["🏰", "castle"],
  ["💒", "wedding"],
  ["🗼", "Tokyo tower"],
  ["🗽", "Statue of Liberty"],
  ["⛪", "church"],
  ["🕌", "mosque"],
  ["🛕", "hindu temple"],
  ["🕍", "synagogue"],
  ["⛩️", "shinto shrine"],
  ["⛩", "shinto shrine"],
  ["🕋", "kaaba"],
  ["⛲", "fountain"],
  ["⛺", "tent"],
  ["🌁", "foggy"],
  ["🌃", "night with stars"],
  ["🏙️", "cityscape"],
  ["🌄", "sunrise over mountains"],
  ["🌅", "sunrise"],
  ["🌆", "cityscape at dusk"],
  ["🌇", "sunset"],
  ["🌉", "bridge at night"],
  ["🎑", "moon viewing ceremony"],
  ["♨️", "hot springs"],
  ["🎠", "carousel horse"],
  ["🛝", "playground slide"],
  ["🎡", "ferris wheel"],
  ["🎢", "roller coaster"],
  ["💈", "barber pole"],
  ["🎪", "circus tent"],
  ["🚂", "locomotive"],
  ["🚃", "railway car"],
  ["🚄", "high-speed train"],
  ["🚅", "bullet train"],
  ["🚆", "train"],
  ["🚇", "metro"],
  ["🚈", "light rail"],
  ["🚉", "station"],
  ["🚊", "tram"],
  ["🚝", "monorail"],
  ["🚞", "mountain railway"],
  ["🚋", "tram car"],
  ["🚌", "bus"],
  ["🚍", "oncoming bus"],
  ["🚎", "trolleybus"],
  ["🚐", "minibus"],
  ["🚑", "ambulance"],
  ["🚒", "fire engine"],
  ["🚓", "police car"],
  ["🚔", "oncoming police car"],
  ["🚕", "taxi"],
  ["🚖", "oncoming taxi"],
  ["🚗", "automobile"],
  ["🚘", "oncoming automobile"],
  ["🚙", "sport utility vehicle"],
  ["🛻", "pickup truck"],
  ["🚚", "delivery truck"],
  ["🚛", "articulated lorry"],
  ["🚜", "tractor"],
  ["🏎️", "racing car"],
  ["🏍️", "motorcycle"],
  ["🛵", "motor scooter"],
  ["🦽", "manual wheelchair"],
  ["🦼", "motorized wheelchair"],
  ["🛺", "auto rickshaw"],
  ["🚲", "bicycle"],
  ["🛴", "kick scooter"],
  ["🛹", "skateboard"],
  ["🛼", "roller skate"],
  ["🚏", "bus stop"],
  ["🛣️", "motorway"],
  ["🛣", "motorway"],
  ["🛤️", "railway track"],
  ["⛵", "sailboat"],
  ["🛶", "canoe"],
  ["🚤", "speedboat"],
  ["🛳️", "passenger ship"],
  ["⛴️", "ferry"],
  ["⛴", "ferry"],
  ["🛥️", "motor boat"],
  ["🚢", "ship"],
  ["✈️", "airplane"],
  ["🛩️", "small airplane"],
  ["🛫", "airplane departure"],
  ["🛬", "airplane arrival"],
  ["🪂", "parachute"],
  ["💺", "seat"],
  ["🚁", "helicopter"],
  ["🚟", "suspension railway"],
  ["🚠", "mountain cableway"],
  ["🚡", "aerial tramway"],
];
